@localhost = http://localhost:5106

POST {{localhost}}/movies/new
Content-Type: application/json

{
  "year": "2002",
  "name": "Matrix",
  "classification": "G",
  "cast": [
    "Keanu Reeves",
    "Jhon Doe"
  ],
  "duration": 120,
  "imageUrl": "https://placehold.co/250x300/png",
  "synopsis": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  "category": "Fiction",
  "rating": 4.9
}

###
POST {{localhost}}/movies/new
Content-Type: application/json

{
  "name": "Matrix Reload",
  "classification": "G",
  "cast": [
    "Keanu Reeves",
    "Jhon Doe"
  ],
  "duration": 120,
  "imageUrl": "https://placehold.co/250x300/png",
  "synopsis": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  "category": "Fiction",
  "rating": 4.9
}

###
POST {{localhost}}/movies/new
Content-Type: application/json

{
  "name": "Revolver",
  "classification": "G",
  "cast": [
    "Keanu Reeves",
    "Jhon Doe"
  ],
  "duration": 120,
  "imageUrl": "https://placehold.co/250x300/png",
  "synopsis": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  "category": "Action",
  "rating": 4.9
}